schema_version = "1.0.0"

id = "blend_et"
version = "1.3.2"
name = "BlendET"
tagline = "Blender Plugin for scientific visualization"
maintainer = "Hayk Hakobyan <haykh.astro@gmail.com>"
type = "add-on"

website = "https://github.com/haykh/blend-et/"

tags = [
  "Add Mesh",
  "Geometry Nodes",
  "Import-Export",
  "Material",
  "Mesh",
  "Node",
  "User Interface",
]

blender_version_min = "5.0.0"

license = ["SPDX:GPL-3.0-or-later"]
