schema_version = "1.0.0"

id = "blend_et"
version = "1.3.4"
name = "BlendET"
tagline = "Tools to streamline scientific visualization"
maintainer = "Hayk Hakobyan <haykh.astro@gmail.com>"
type = "add-on"

website = "https://github.com/haykh/blend-et/"

tags = [
  "Add Mesh",
  "Geometry Nodes",
  "Import-Export",
  "Material",
  "Mesh",
  "Node",
  "User Interface",
]

blender_version_min = "4.5.0"

license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2024-2026 Hayk Hakobyan"]

[permissions]
files = "Import data (.vdb/.npy/.npz) and write .vdb / rendered LaTeX"

# DISCLAIMER:
# the add-on executes a subprocess to run LaTeX commands (latex/pdflatex/xelatex/dvisvgm)
# to generate SVGs from LaTeX code, which are then imported into Blender as curves.

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "/tests/",
  "/docs/",
  "/.vscode/",
  "/examples/",
  "/testdata/",
  "/scratch/",
  "/.venv/",
  "/.ruff_cache/",
  "/legacy/",
  "/pyrefly.toml",
  "/ruff.toml",
  "/requirements.txt",
  "/README.md",
  "/.gitattributes",
  "/.gitignore",
]
